name: kLMS
version: '${project.version}'
main: ro.kmagic.klms.KLMS
authors: [ kMagic ]
description: Adds the Last Man Standing game to Minecraft.
softdepend:
  - PlaceholderAPI

commands:
  lms:
    description: Infos about this plugin.

permissions:
  superlms.admin:
    description: Access to powerfull commands like reloadand configuration commands.
    default: op
  superlms.join:
    description: Access to /lms join command.
    default: op
  superlms.exit:
    description: Access to /lms exit command.
    default: op
  superlms.spectate:
    description: Access to /lms spectate command.
    default: op